language: go

go:
  - "1.8"
  - "1.10.x"
  - master

before_install:
  - go get github.com/grafov/m3u8
  - go get github.com/mattn/goveralls

script:
  - go test -v -covermode=count -coverprofile=coverage.out
  - $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci
